spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:security;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
  jpa:
    database: h2
    show-sql: true
    hibernate:
      ddl-auto: create-drop